package repulnyil;

import java.util.ArrayList;
import java.util.List;

public class Jaratszerkeszto extends javax.swing.JFrame {

    private List<Orszag> orszagok = new ArrayList();
    
    public Jaratszerkeszto() {
        initComponents();
        this.orszagok.add(new Orszag ("Magyarország", "Budapest"));
             this.orszagok.get(0).addCelorszagNevek("Belgium");
             this.orszagok.get(0).addCelorszagNevek("Anglia");
             this.orszagok.get(0).addCelorszagNevek("Csehország");
        this.orszagok.add(new Orszag ("Németország", "Berlin"));
             this.orszagok.get(1).addCelorszagNevek("Anglia");
             this.orszagok.get(1).addCelorszagNevek("USA");
             this.orszagok.get(1).addCelorszagNevek("Oroszország");
        this.orszagok.add(new Orszag ("Irán", "Teherán"));
             this.orszagok.get(2).addCelorszagNevek("Irak");
             this.orszagok.get(2).addCelorszagNevek("Oroszország");
             this.orszagok.get(2).addCelorszagNevek("India");
        this.orszagok.add(new Orszag ("USA", "Washington DC:"));
             this.orszagok.get(3).addCelorszagNevek("Kanada");
             this.orszagok.get(3).addCelorszagNevek("Belgium");
             this.orszagok.get(3).addCelorszagNevek("Németország");  
        this.orszagok.add(new Orszag ("Spanyolország", "Madrid"));
             this.orszagok.get(4).addCelorszagNevek("Magyarország");
        this.orszagok.add(new Orszag ("Japán", "Tokió"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lstOrszagok = new javax.swing.JComboBox<>();
        pnlCelorszagok = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Ország kivályasztása: ");

        javax.swing.GroupLayout pnlCelorszagokLayout = new javax.swing.GroupLayout(pnlCelorszagok);
        pnlCelorszagok.setLayout(pnlCelorszagokLayout);
        pnlCelorszagokLayout.setHorizontalGroup(
            pnlCelorszagokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlCelorszagokLayout.setVerticalGroup(
            pnlCelorszagokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lstOrszagok, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCelorszagok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lstOrszagok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCelorszagok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        this.pnlCelorszagok.setVisible(false);
        
        this.lstOrszagok.addItem("Válasszon");
        for(Orszag orsz : this.orszagok){
            this.lstOrszagok.addItem(orsz.getNev());
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jaratszerkeszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jaratszerkeszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jaratszerkeszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jaratszerkeszto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jaratszerkeszto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> lstOrszagok;
    private javax.swing.JPanel pnlCelorszagok;
    // End of variables declaration//GEN-END:variables
}
